[COL-14] Duomenų bazės implementacija
pkondratas/Collibri pull request #42
Opened 2023-10-30 21:05 UTC by jogis0

Čia rodo daug failų pakeista, nes tiesiog perdėjau į kitas direktorijas, kad aiškiau būtų.

- Perdariau programos modelius, kad veiktų su duomenų baze. Dabar modelių klasės nebeturi konstruktoriaus, nes kitaip man rodos neina padaryt. Testuose dabar sukurt modelio objektą galim pasinaudojant {} skliaustelius (pvz.: `new Room(){Id = 1, Name = "roomName"}`).
- Sukurta DataContext klasė duomenims iš duombazės doroti. Dabar vietoj DataHandler'io galima kviesti DataContext klasę ir iš ten, pagal tam tikrą DbSet'ą, ištraukt duomenis iš duomenų bazės.
- Sukūriau atskiras repozitorijas duomenų bazės implementacijai.
- Pataisiau testų data klases, bet vis dar reikia pakeisti testus (nes iš pradžių kai darėm per daug fieldų buvom priskyrę model klasėm)

2023-10-30 22:22 UTC, mantvydasMac approved these changes

2023-10-31 14:32 UTC, pkondratas requested changes
Tikiuos nieko nepamirsau, bet lyg ir tiek. Viskas atrodo veikia, veliau paugradinsim su virtual ir partial kaip rode pratybose.

2023-10-31 14:32 UTC, pkondratas commented on Collibri/Repositories/DbImplementation/DbSectionRepository.cs
> +        if (_context.Sections.Any(sections => sections.Equals(section)))
cia reikia _context.Sections.ToList(),Any del custom equal, arba pakeist, kad nebutu to metodo isvis sekcijoj ir butu ta salyga linq

2023-10-31 14:32 UTC, pkondratas commented on Collibri/Repositories/FileRepository.cs
> +using Collibri.Models;
Sitas failas turetu but prie filebasedimplementation irgi, ne?

2023-10-31 14:32 UTC, pkondratas commented on Collibri/Repositories/FileRepository.cs
> +			var room = new Room() { Id = 5, Name = "name" };
cia sitas turi but?

2023-10-31 14:32 UTC, pkondratas commented on Collibri/appsettings.json
> +    "LocalConnection": "Server=localhost;Port=5432;Database=postgres;Username=postgres;Password=admin"
cia gal passwordo reiketu nerodyt, palikt tik lygu, o tada kiekvienas isives

2023-10-31 14:32 UTC, pkondratas commented on Collibri/Models/Document.cs
> +        // public Document(int id, Guid postId, string title, string text)
cia visus konstruktorius galima palikt, tik reikia pridet tuscia konstruktoriu. Sita reikia padaryt visiem ir turi veikt tada

2023-10-31 14:32 UTC, pkondratas commented on Collibri/Repositories/DbImplementation/DbDocumentRepository.cs
> +namespace Collibri.Repositories.DbImplementation;
{} po namespace'o(ir kituose)

2023-10-31 16:11 UTC, pkondratas requested changes

2023-10-31 16:11 UTC, pkondratas commented on Collibri/Repositories/DbImplementation/DbNoteRepository.cs
> +            note.CreationDate = DateTime.Now;
Postgrese raso kad reikia kad butu UTC formatas, tai cia ir kitur veikia su UtcNow. Dar pasitikslint reikia ar teisinga data bus tada bet man rodos viskas ok bus

2023-10-31 16:11 UTC, pkondratas commented on Collibri/Repositories/DbImplementation/DbPostRepository.cs
> +            post.LastUpdatedDate = DateTime.Now;
cia irgi

2023-10-31 16:11 UTC, pkondratas commented on Collibri/Repositories/DbImplementation/DbPostRepository.cs
> +            postToUpdate.LastUpdatedDate = DateTime.Now;
cia taip pat

2023-10-31 16:11 UTC, pkondratas commented on Collibri/Repositories/DbImplementation/DbNoteRepository.cs
> +            targetNote.LastUpdatedDate = DateTime.Now;
cia irgi

2023-11-01 15:25 UTC, pkondratas approved these changes
atrodo viskas gerai

2023-11-01 18:38 UTC, merged