Create post modal simple
pkondratas/Collibri pull request #48
Opened 2023-11-06 12:38 UTC by mantvydasMac

Create post modal. Ivedamas title ir description, tada sukuria posta. Paprastas modalas, be note, doc, file pridejimu. Truksta tik pagrazinimo is stiliaus puses ir kad permestu i paprasto posto modala, bet kadangi jo kol kas nera tai bus prideta veliau. Taip pat dar ivauriu sectionId postId fieldu patvarkymai yra, bet tas per daug netestuota.

2023-11-06 13:03 UTC, dovix58 approved these changes
hold up

2023-11-06 13:16 UTC, jogis0 approved these changes, later dismissed
Atrodo gerai

2023-11-06 13:23 UTC, dovix58 requested changes
as cia nezinau ar bugai ar dar nepadaryta tiesiog. Bet dabar galima yra kurt postus, kai nera sectionu, ir tada neina ju istrinti, tai manau sita reikia sufixint. Toliau dar jei yra sekcija su savo postais, istrynus ta sekcija postai pasilieka db ir ju irgi neina istrinti. Beto ten kur CreatePostApi, manau i ta pati postApi galima det ta add nebutinai naujo failo.

2023-11-06 14:01 UTC, jogis0 requested changes
Tai cia sita su CreatePostApi ir kur Dovydas sake

2023-11-06 14:01 UTC, jogis0 commented on Collibri/ClientApp/src/api/CreatePostApi.js
> +export const createPost = (post) => {
Cia gal sita CreatePostApi reiktu perkelt i PostAPI faila

2023-11-07 09:26 UTC, dovix58 approved these changes
Jo db looks good.

2023-11-07 09:28 UTC, jogis0 approved these changes
Dabar tobula

2023-11-07 10:42 UTC, merged