[COL-6, 9, 17, 26] Create, display, delete, update room
pkondratas/Collibri pull request #8
Opened 2023-09-25 19:14 UTC by migle-kirilovaite

Visi kambariai yra saugomi Rooms.json faile. Pakeisti praktiškai visi metodai, kad dirbtu su DataHandling. Parašyti RoomController unit testai. Requestai sukelti į Testfully.

2023-09-25 20:13 UTC, pkondratas requested changes
Apart tu dalyku kur cia parasiau viskas okey atrodo ir galima bus mergint, keletas is ju tiesiog pasiulymai. Reiketu dar testuot ir RoomRepository bet cia galima palikt ir kitam kartui jei nebespesi.

2023-09-25 20:13 UTC, pkondratas commented on Collibri/Controllers/RoomController.cs
> +                return NoContent(); // Return 204 No Content if there are no rooms.
cia sitas galbut nera butinas, kadangi tusciam esant ir grazins []

2023-09-25 20:13 UTC, pkondratas commented on Collibri/Controllers/RoomController.cs
> +            {
tiek cia, tiek delete galima butu padaryt su ... ? ... : ... kaip ir post requeste. aisku veikai ir taip, bet butu visur taip pat ir maziau eiluciu kaip rekomenduojama

2023-09-25 20:13 UTC, pkondratas commented on Collibri/Controllers/RoomController.cs
> +            return NoContent(); // Return 204 No Content to indicate successful deletion.
galima butu grazint body kuris buna istrintas, kad isitikint ar atrastas tikrai tas, bet galima ir taip

2023-09-25 20:13 UTC, pkondratas commented on Collibri/Models/Rooms/IRoomRepository.cs
> +namespace Collibri.RoomModels;
nera namespace'o {}

2023-09-25 20:13 UTC, pkondratas commented on Collibri/Models/Rooms/Room.cs
> +
nera namespace'o {}

2023-09-25 20:13 UTC, pkondratas commented on Collibri/Models/Rooms/RoomRepository.cs
> +            Room existingRoom = roomList.FirstOrDefault(room => room.Id == roomId);
cia neturetu but "Room?" tipas? nes jei nera su tokiu id itemo, bus null ir error'ras

2023-09-25 20:13 UTC, pkondratas commented on Collibri/Models/Rooms/RoomRepository.cs
> +            Room roomToRemove = roomList.FirstOrDefault(room => room.Id == roomId);
cia irgi man rodos turetu but "Room?" tipas

2023-09-25 20:13 UTC, pkondratas commented on Collibri/Models/Rooms/RoomRepository.cs
> +
cia galbut butu gerai sugeneruot id, kad jos nepasint per requestbody/nebutu tuscia

2023-09-25 20:36 UTC, jogis0 approved these changes

2023-09-25 20:36 UTC, jogis0 commented on Collibri.Tests/Controllers/RoomControllerTest.cs
> +        mockRepo.Setup(repo => repo.CreateRoom(roomToCreate)).Returns(roomToCreate);
Čia nežinau, bet gal būtų galima kažkaip testų data perkelti į kitą klasę, kad patogiau būtų testuot ir patogiau matyt, kas ką turėtu daryt. Dabar viskas ok, bet kiek žinau paskui gali būti sunkiau įskaityt, kai bus daugiau testų ir daugiau data.

2023-09-25 20:36 UTC, jogis0 commented on Collibri/Program.cs
> +using Collibri.RoomModels;
Man rodos, kad šito nereikia, nes kaip ir nėra tokios direktorijos. Bet gali būt, kad aš klystu

2023-09-26 07:10 UTC, pkondratas approved these changes

2023-09-26 07:13 UTC, merged